services:
  weather-collector:
    build:
      context: ..
      dockerfile: dockerfile/Dockerfile
    volumes:
      - ../data:/app/data
      - ../logs:/app/logs
    environment:
    - PYTHONUNBUFFERED=1
    restart: unless-stopped
    command: ["python", "src/scheduler.py"]

  weather-processor:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ../data:/app/data
      - ../logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    command: ["python", "src/process_scheduler.py"]