version: '3'

services:
  postgres:
    image: postgres:14
    container_name: weatherflow-postgres
    environment:
      - POSTGRES_USER=weatherflow
      - POSTGRES_PASSWORD=weatherflow
      - POSTGRES_DB=weatherflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U weatherflow"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: